sudo: required
language: python
python:
  - "3.5"

services:
  - docker

before_install:
  # We put all environment variables with TRAVIS_ in the beginning in a file to read it later (e.g., for github token)
  - printenv | grep -E '^TRAVIS_' > .env
  - docker build -t testdocker .
  - docker network create -d bridge mongodb-net
  - docker run -d --net=mongodb-net --name=mongo_db mongo:3.4

install:
  - docker run testdocker /bin/sh -c "cd /root/mecoshark; python3.5 setup.py install"

script:
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/mecoshark; python3.5 setup.py test"

after_success:
  - docker run --env-file .env testdocker /bin/sh -c "cd /root/mecoshark; make deploy > /dev/null"